import React, { useState, useMemo } from 'react';
import { 
  Crosshair, 
  ShieldAlert, 
  ExternalLink, 
  Copy, 
  Check, 
  Layers, 
  Terminal, 
  Cpu, 
  AlertTriangle,
  Globe,
  Server,
  User,
  Zap,
  CheckCircle2,
  Info
} from 'lucide-react';
import { EmailAnalysis } from '../types';
import { mapMitreAttackTechniques } from '../utils/mitreMapping';

interface MitreAttackDossierProps {
  analysis: EmailAnalysis;
  className?: string;
}

export function MitreAttackDossier({ analysis, className = '' }: MitreAttackDossierProps) {
  const [copiedRule, setCopiedRule] = useState<string | null>(null);

  // 1. Dynamic Real MITRE Techniques
  const techniques = useMemo(() => {
    return mapMitreAttackTechniques(analysis);
  }, [analysis]);

  // Extract real infrastructure data
  const hops = Array.isArray(analysis?.hops) ? analysis.hops : [];
  const firstHop = hops.find(h => h.isOrigin) || hops[0];
  const originIp = (analysis as any)?.senderIp || firstHop?.fromIp || 'N/A';
  const originAsn = firstHop?.asn || 'N/A';
  const originIsp = firstHop?.isp || firstHop?.org || 'External Origin';
  const originLocation = firstHop?.city ? `${firstHop.city}, ${firstHop.country}` : (firstHop?.country || 'Unknown Geolocation');
  
  const fromEmail = analysis?.from?.match(/<([^>]+)>/)?.[1] || analysis?.from || 'unknown@sender.com';
  const fromDomain = fromEmail.split('@')[1] || 'sender-domain.com';
  const victimEmail = analysis?.to || analysis?.headers?.to || 'internal-recipient';

  // 2. Dynamic Real YARA Rule generated from observed evidence
  const dynamicYaraRule = useMemo(() => {
    const caseId = (analysis?.id || 'CASE').replace(/[^a-zA-Z0-9_]/g, '_');
    const strings: string[] = [];
    
    if (fromDomain && fromDomain !== 'sender-domain.com') {
      strings.push(`        $domain = "${fromDomain}" ascii nocase`);
    }
    if (originIp && originIp !== 'N/A') {
      strings.push(`        $ip = "${originIp}" ascii`);
    }
    if (Array.isArray(analysis?.attachments) && analysis.attachments.length > 0) {
      analysis.attachments.forEach((a, i) => {
        if (a.filename) {
          strings.push(`        $att_${i} = "${a.filename}" ascii nocase`);
        }
      });
    }
    if (Array.isArray(analysis?.urls) && analysis.urls.length > 0) {
      const firstUrl = typeof analysis.urls[0] === 'string' ? analysis.urls[0] : analysis.urls[0].url;
      try {
        const parsed = new URL(firstUrl);
        strings.push(`        $url_host = "${parsed.hostname}" ascii nocase`);
      } catch {
        strings.push(`        $url = "${firstUrl.slice(0, 40)}" ascii nocase`);
      }
    }

    if (strings.length === 0) {
      strings.push(`        $subject = "${(analysis?.subject || 'Malicious Email').replace(/"/g, '\\"')}" ascii nocase`);
    }

    return `rule TXM_IOC_${caseId} {
    meta:
        description = "Autogenerated forensic detection rule for case ${analysis?.id || 'CASE-2026'}"
        source = "TraceXMail Forensic Core"
        date = "${new Date().toISOString().split('T')[0]}"
        threat_score = "${analysis?.threatScore || (analysis as any)?.threat_score || 85}/100"
    strings:
${strings.join('\n')}
    condition:
        any of ($*)
}`;
  }, [analysis, fromDomain, originIp]);

  // 3. Dynamic Real Sigma Rule generated from observed evidence
  const dynamicSigmaRule = useMemo(() => {
    const caseId = (analysis?.id || 'CASE').replace(/[^a-zA-Z0-9_-]/g, '-');
    return `title: Inbound Phishing IOC - Case ${analysis?.id || 'CASE'}
id: ${caseId}
status: production
description: Detects inbound email matching observed IOC telemetry
references:
    - https://tracexmail.sec/cases/${analysis?.id || 'CASE'}
author: TraceXMail Threat Engine
date: ${new Date().toISOString().split('T')[0]}
logsource:
    category: email
    product: m365_exchange
detection:
    selection:
        SenderDomain: '${fromDomain}'
        ${originIp !== 'N/A' ? `OriginIP: '${originIp}'` : ''}
    condition: selection
fields:
    - Sender
    - Recipient
    - MessageId
level: high`;
  }, [analysis, fromDomain, originIp]);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedRule(id);
    setTimeout(() => setCopiedRule(null), 2000);
  };

  return (
    <div className={`rounded-xl border border-slate-800 bg-[#0e1017] p-5 shadow-lg ${className}`}>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-4 mb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-red-500/20 border border-red-500/40 flex items-center justify-center text-red-400">
            <Crosshair className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-mono text-xs font-bold text-white uppercase tracking-wider">
                MITRE ATT&amp;CK® Matrix &amp; Threat Forensics
              </span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-purple-500/10 text-purple-300 border border-purple-500/30">
                DYNAMIC MATRIX ({techniques.length} TECHNIQUES OBSERVED)
              </span>
            </div>
            <span className="text-[11px] text-slate-400">
              Correlated against observed header, route, and authentication telemetry for this specific email.
            </span>
          </div>
        </div>
      </div>

      {/* Dynamic Diamond Model for Intrusion Analysis */}
      <div className="mb-6 rounded-lg border border-slate-800 bg-slate-950/60 p-4 font-mono text-xs">
        <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
          <Layers className="w-3.5 h-3.5 text-purple-400" />
          <span>Dynamic Diamond Model (Grounded in Observed IOCs)</span>
        </div>
        
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {/* Adversary */}
          <div className="p-3 rounded bg-slate-900/80 border border-purple-500/30">
            <div className="text-[10px] uppercase text-purple-400 font-bold mb-1 flex items-center gap-1">
              <User className="w-3 h-3" />
              <span>Adversary / Sender</span>
            </div>
            <div className="font-bold text-white text-xs mb-1 truncate">{fromDomain}</div>
            <div className="text-[11px] text-slate-400 font-sans">
              Sender envelope: <code className="text-purple-300 text-[10px]">{fromEmail}</code>
            </div>
          </div>

          {/* Capability */}
          <div className="p-3 rounded bg-slate-900/80 border border-rose-500/30">
            <div className="text-[10px] uppercase text-rose-400 font-bold mb-1 flex items-center gap-1">
              <Zap className="w-3 h-3" />
              <span>Observed Vector</span>
            </div>
            <div className="font-bold text-white text-xs mb-1">
              {techniques.length > 0 ? techniques[0].name : 'Inbound SMTP Ingestion'}
            </div>
            <div className="text-[11px] text-slate-400 font-sans">
              Auth: SPF ({typeof analysis?.auth?.spf === 'object' ? analysis.auth.spf.status : (analysis?.auth?.spf || 'N/A')}), DMARC ({typeof analysis?.auth?.dmarc === 'object' ? analysis.auth.dmarc.status : (analysis?.auth?.dmarc || 'N/A')})
            </div>
          </div>

          {/* Infrastructure */}
          <div className="p-3 rounded bg-slate-900/80 border border-amber-500/30">
            <div className="text-[10px] uppercase text-amber-400 font-bold mb-1 flex items-center gap-1">
              <Server className="w-3 h-3" />
              <span>Origin Infrastructure</span>
            </div>
            <div className="font-bold text-white text-xs mb-1 truncate">{originIp}</div>
            <div className="text-[11px] text-slate-400 font-sans">
              ASN {originAsn} • {originIsp} ({originLocation})
            </div>
          </div>

          {/* Victim */}
          <div className="p-3 rounded bg-slate-900/80 border border-sky-500/30">
            <div className="text-[10px] uppercase text-sky-400 font-bold mb-1 flex items-center gap-1">
              <Globe className="w-3 h-3" />
              <span>Target Victim</span>
            </div>
            <div className="font-bold text-white text-xs mb-1 truncate">{victimEmail}</div>
            <div className="text-[11px] text-slate-400 font-sans">
              Targeted mailbox in analyzed incident docket
            </div>
          </div>
        </div>
      </div>

      {/* MITRE ATT&CK Matrix Techniques Table */}
      <div className="mb-6 font-mono text-xs">
        <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
          <Terminal className="w-3.5 h-3.5 text-red-400" />
          <span>Dynamically Triggered ATT&amp;CK Techniques ({techniques.length})</span>
        </div>

        {techniques.length === 0 ? (
          <div className="p-4 rounded-lg bg-slate-900/60 border border-slate-800 text-slate-400 flex items-center gap-2">
            <Info className="w-4 h-4 text-slate-500" />
            <span>No malicious ATT&amp;CK tactics triggered for this clean message.</span>
          </div>
        ) : (
          <div className="rounded-lg border border-slate-800 overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-900 text-slate-400 text-[10px] uppercase border-b border-slate-800">
                  <th className="p-2.5">Technique ID</th>
                  <th className="p-2.5">Name &amp; Tactic</th>
                  <th className="p-2.5">Confidence</th>
                  <th className="p-2.5">Observed Proof in Case</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 bg-[#12141c]">
                {techniques.map((tech) => (
                  <tr key={tech.id} className="hover:bg-slate-800/30 transition-colors">
                    <td className="p-2.5 font-bold text-red-400">
                      <a 
                        href={tech.url} 
                        target="_blank" 
                        rel="noreferrer" 
                        className="px-1.5 py-0.5 rounded bg-red-950/80 border border-red-800 hover:border-red-600 transition-colors inline-flex items-center gap-1"
                      >
                        <span>{tech.id}</span>
                        <ExternalLink className="w-2.5 h-2.5 text-slate-400" />
                      </a>
                    </td>
                    <td className="p-2.5">
                      <div className="font-semibold text-white">{tech.name}</div>
                      <div className="text-[10px] text-slate-400">{tech.tactic}</div>
                    </td>
                    <td className="p-2.5 text-emerald-400 font-semibold text-[11px]">
                      {tech.confidence}
                    </td>
                    <td className="p-2.5 text-slate-300 font-sans text-xs">
                      {tech.detectedProof}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Dynamic YARA & Sigma Threat Signatures */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-xs">
        {/* Real Dynamic YARA Rule */}
        <div className="rounded-lg border border-slate-800 bg-slate-950 p-3 space-y-2">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <span className="text-[11px] font-bold text-amber-400 uppercase">Live YARA Rule (Built from this Case)</span>
            <button
              type="button"
              onClick={() => copyToClipboard(dynamicYaraRule, 'yara')}
              className="text-[10px] text-slate-400 hover:text-white flex items-center gap-1 transition-colors cursor-pointer"
            >
              {copiedRule === 'yara' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
              <span>{copiedRule === 'yara' ? 'Copied' : 'Copy YARA'}</span>
            </button>
          </div>
          <pre className="text-[10px] text-slate-300 overflow-x-auto p-2 bg-black/40 rounded leading-relaxed">
            {dynamicYaraRule}
          </pre>
        </div>

        {/* Real Dynamic Sigma SIEM Rule */}
        <div className="rounded-lg border border-slate-800 bg-slate-950 p-3 space-y-2">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <span className="text-[11px] font-bold text-sky-400 uppercase">Live Sigma SIEM Rule (Built from this Case)</span>
            <button
              type="button"
              onClick={() => copyToClipboard(dynamicSigmaRule, 'sigma')}
              className="text-[10px] text-slate-400 hover:text-white flex items-center gap-1 transition-colors cursor-pointer"
            >
              {copiedRule === 'sigma' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
              <span>{copiedRule === 'sigma' ? 'Copied' : 'Copy Sigma'}</span>
            </button>
          </div>
          <pre className="text-[10px] text-slate-300 overflow-x-auto p-2 bg-black/40 rounded leading-relaxed">
            {dynamicSigmaRule}
          </pre>
        </div>
      </div>
    </div>
  );
}
