import fs from 'fs';
import path from 'path';

// Let's create a rich, realistic generator where every single email has distinct vocabulary and phrasing
export function getRichCorpusCandidates() {
  const legit: Array<{ subject: string; text: string; from: string; domain: string }> = [
    // 1-20: Cloud, SRE & Infra
    { subject: 'AWS Maintenance: RDS PostgreSQL multi-AZ failover test complete', text: 'Amazon Web Services completed the planned chaos engineering failover drill on database cluster aurora-pg-prod. Secondary replica in us-east-1b assumed master role in 14 seconds without packet drop.', from: 'AWS Notifications <no-reply@amazon.com>', domain: 'amazon.com' },
    { subject: 'Cloudflare: Origin SSL certificate auto-renewed for tracexmail.dev', text: 'Your Cloudflare Origin CA certificate covering *.tracexmail.dev has been reissued for a 15-year term. No manual key exchange or server restart is necessary.', from: 'Cloudflare <no-reply@cloudflare.com>', domain: 'cloudflare.com' },
    { subject: 'Google Cloud Spanner: Monthly node allocation and storage metrics', text: 'Monthly metrics for Spanner instance spanner-telemetry-01: 99.999% availability, average commit latency 8.2ms, total compressed storage footprint 420 GB.', from: 'Google Cloud <google-cloud-noreply@google.com>', domain: 'google.com' },
    { subject: 'Datadog Alert: [RESOLVED] High connection pool exhaustion on redis-cache', text: 'Metric redis.connections.used on cluster cache-01 returned to 34% (threshold: 80%). The automated connection reaper successfully closed idle worker connections.', from: 'Datadog Alerts <alerts@datadoghq.com>', domain: 'datadoghq.com' },
    { subject: 'Sentry: Unhandled TypeError resolved in release 2.4.2 by Alex Rivers', text: 'Issue #48192 (Cannot read properties of null in extractDomainHeader) was marked resolved by Alex Rivers via commit 4a910bf.', from: 'Sentry <notifications@getsentry.com>', domain: 'getsentry.com' },
    { subject: 'Terraform Cloud: Run #8491 applied successfully in workspace prod-vpc', text: 'Workspace prod-vpc applied by Sarah Jenkins. 3 resources updated, 0 destroyed. Outputs: public_subnet_ids = [subnet-01, subnet-02].', from: 'Terraform Cloud <notifications@hashicorp.com>', domain: 'hashicorp.com' },
    { subject: 'Fastly: Edge cache hit ratio reached 94.2% over past 30 days', text: 'Your Fastly service delivered 48 million edge requests. Origin traffic was reduced by 94.2%. P99 time to first byte was 22ms globally.', from: 'Fastly Support <support@fastly.com>', domain: 'fastly.com' },
    { subject: 'Docker Hub: Automated security vulnerability scan report for tag v2.4.2', text: 'Docker Scout scanned tracex/backend:v2.4.2. 0 Critical, 0 High, 1 Low CVE detected in libexpat. Image cleared for production cluster deployment.', from: 'Docker Hub <hub-noreply@docker.com>', domain: 'docker.com' },
    { subject: 'PagerDuty: Post-mortem timeline published for Sev-2 Incident #9481', text: 'Incident #9481 (Webhook queue delay) post-mortem draft is available for review in Confluence. Action item: increase consumer concurrency during traffic spikes.', from: 'PagerDuty <no-reply@pagerduty.com>', domain: 'pagerduty.com' },
    { subject: 'ArgoCD: Cluster prod-us-east-1 synced with Git revision 8b4f10a', text: 'Application tracex-worker-pool successfully synced with Git repository. All 16 pods transitioned to Healthy and Running status.', from: 'ArgoCD <argocd@corp.internal>', domain: 'corp.internal' },

    // 21-40: Developer, GitHub, GitLab & Tooling
    { subject: '[GitHub] Pull request #904 approved: test(classifier): add unit tests for RFC 5322', text: 'David Kim has approved your pull request. The CI matrix completed in 3m 40s across Ubuntu and macOS runners. 142 tests passing.', from: 'GitHub <notifications@github.com>', domain: 'github.com' },
    { subject: 'GitLab: Pipeline #49102 succeeded on branch release-2.5', text: 'All jobs in pipeline #49102 succeeded. Cypress end-to-end suite passed without retries. Release tarball published to package registry.', from: 'GitLab CI <gitlab-runner@gitlab.com>', domain: 'gitlab.com' },
    { subject: 'npm security: Zero high-severity vulnerabilities found in dependency tree', text: 'The weekly automated audit for package.json completed. All 84 production dependencies are up to date and verified against GitHub Advisory Database.', from: 'npm Registry <support@npmjs.com>', domain: 'npmjs.com' },
    { subject: 'CircleCI: Workflow build-and-test completed for commit e4810ab', text: 'Job build-and-test finished in 4m 12s on runner cimg/node:20.18. Artifacts archived: coverage/lcov.info (98.4% statement coverage).', from: 'CircleCI <notifications@circleci.com>', domain: 'circleci.com' },
    { subject: 'Jira Software: [ENG-402] Implement adaptive Brier score calculation closed', text: 'Marcus Vance changed status of ENG-402 to COMPLETED. Acceptance criteria: compute calibration curves across 10 confidence bins.', from: 'Jira <jira@atlassian.net>', domain: 'atlassian.net' },
    { subject: 'JetBrains: Commercial license allocation for WebStorm IDE confirmed', text: 'Your JetBrains All Products Pack subscription seat has been assigned by your team admin. Activate using your corporate JetBrains Account.', from: 'JetBrains <sales@jetbrains.com>', domain: 'jetbrains.com' },
    { subject: 'Snyk: Daily vulnerability monitoring summary for tracexmail-monorepo', text: 'Snyk tested 1,420 dependencies across 4 packages. 0 open issues. Dependency health score: 98/100.', from: 'Snyk <notifications@snyk.io>', domain: 'snyk.io' },
    { subject: 'Postman: Team workspace collection updated with new v2.5 endpoints', text: 'Elena Rostova updated collection "TraceXMail Forensic API v2.5". 4 new request examples added for header analysis and ML metrics.', from: 'Postman <notifications@postman.com>', domain: 'postman.com' },
    { subject: 'SonarQube: Quality Gate passed for project tracexmail-core', text: 'SonarCloud analysis completed: 0 Bugs, 0 Vulnerabilities, 0 Security Hotspots, 0.0% Duplication on 8,400 lines of new code.', from: 'SonarCloud <notifications@sonarcloud.io>', domain: 'sonarcloud.io' },
    { subject: 'Bitbucket: Branch feature/meta-classifier created by Sarah Jenkins', text: 'Sarah Jenkins pushed new branch feature/meta-classifier to tracexmail/backend. 4 commits ahead of main.', from: 'Bitbucket <notifications@bitbucket.org>', domain: 'bitbucket.org' },

    // 41-60: Workplace, IT & Corporate Operations
    { subject: 'Internal IT: Windows 11 Enterprise cumulative security patch rollup', text: 'The corporate IT team will push Microsoft KB5042841 to all managed enterprise laptops tonight at 23:00 local time. Please save open work and reboot.', from: 'Corporate IT <it-ops@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Workplace Operations: Seattle office 3rd floor quiet focus rooms reopen', text: 'Acoustic baffle installation in rooms 301-306 has finished. Focus rooms are available for reservation on Google Calendar starting tomorrow morning.', from: 'Facilities <facilities@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Information Security: Reminder: YubiKey hardware token firmware check', text: 'Infosec is auditing YubiKey 5 Series firmware versions. Insert your token into your laptop and visit our internal verification page to verify.', from: 'Infosec <infosec@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'People Operations: Q4 performance feedback cycle opens on Monday', text: 'Our biannual peer feedback cycle begins next Monday. Complete self-evaluations and nominate up to 4 peer reviewers in Lattice before Oct 24.', from: 'People Ops <people@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Corporate Communications: All-Hands recording and presentation slides', text: 'Thank you for attending today\'s global town hall. The video recording and CEO slide deck are uploaded to the internal intranet portal.', from: 'Internal Comms <comms@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Benefits Administration: Flu vaccination clinic scheduled on-site next week', text: 'Free seasonal influenza vaccines will be offered in the 2nd floor wellness suite on Tuesday and Thursday from 9 AM to 3 PM. Walk-ins welcome.', from: 'Wellness Team <wellness@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Travel & Expense: Q3 corporate card expense reconciliation reminder', text: 'Please ensure all September business expenses are submitted and coded with appropriate project cost centers in Brex before Friday COB.', from: 'Finance <finance@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Legal: Annual code of conduct and ethics compliance acknowledgment', text: 'All full-time employees and contractors must review the updated corporate ethics policy and complete the digital acknowledgment in Navex.', from: 'Legal <legal@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Talent Acquisition: Referral bonus program updates for senior engineering roles', text: 'Earn up to $5,000 for successful engineering referrals. We are hiring Staff Security Engineers and Distributed Systems Leads in Chicago and remote.', from: 'Recruiting <recruiting@internal-enterprise.com>', domain: 'internal-enterprise.com' },
    { subject: 'Facilities: Bicycle storage room seasonal deep cleaning on Saturday', text: 'Building staff will power-wash the basement bike corral this weekend. Bicycles should be locked in the temporary rack on ground level.', from: 'Building Mgmt <facilities@internal-enterprise.com>', domain: 'internal-enterprise.com' },

    // 61-80: Billing, Receipts & SaaS Subscriptions
    { subject: 'Stripe: Your monthly tax invoice for GitHub Team ($79.00 USD)', text: 'Payment of $79.00 was successfully charged to corporate Visa ending in 9012 for 10 GitHub Team seats. Download PDF invoice at billing.stripe.com.', from: 'Stripe Billing <receipts@stripe.com>', domain: 'stripe.com' },
    { subject: 'Google Workspace: Monthly invoice #GOOG-4891024 paid ($48.00)', text: 'Google Payments has processed $48.00 for your 4 Google Workspace Business accounts. Thank you for your continued business.', from: 'Google Payments <payments-noreply@google.com>', domain: 'google.com' },
    { subject: 'Zoom: Monthly subscription invoice #INV-94812 ($149.90)', text: 'Thank you for your payment. Your Zoom Business plan renewal for 10 hosts was billed to corporate Mastercard ending in 4104.', from: 'Zoom Billing <billing@zoom.us>', domain: 'zoom.us' },
    { subject: 'Slack: Monthly receipt for Enterprise Grid ($360.00)', text: 'We received your payment of $360.00 for the billing period October 1 to November 1. View your payment history in Slack Admin.', from: 'Slack Billing <billing@slack.com>', domain: 'slack.com' },
    { subject: 'Figma: Invoice #FIG-48190 for Organization tier seats ($90.00)', text: 'Hi Team, here is your invoice for 6 Figma Professional design seats. Payment charged to corporate card ending in 8491.', from: 'Figma Billing <billing@figma.com>', domain: 'figma.com' },
    { subject: 'DigitalOcean: Monthly droplet and load balancer invoice ($28.50)', text: 'Your monthly charges for 2 Basic droplets and 1 managed cloud load balancer have been charged to your primary payment method.', from: 'DigitalOcean <support@digitalocean.com>', domain: 'digitalocean.com' },
    { subject: 'Twilio: Auto-recharge confirmation ($50.00 added to account balance)', text: 'Your Twilio developer project has been automatically topped up with $50.00. Current account balance: $68.42.', from: 'Twilio <billing@twilio.com>', domain: 'twilio.com' },
    { subject: 'Postmark: Monthly transactional email delivery invoice ($15.00)', text: 'Your Postmark subscription for 10,000 monthly transactional emails was renewed. Delivery rate remained at 99.98% with 0 bounces.', from: 'Postmark <support@postmarkapp.com>', domain: 'postmarkapp.com' },
    { subject: 'Vercel: Monthly invoice #INV-VERCEL-4891 for Pro team ($40.00)', text: 'Your monthly bill for 2 Vercel Pro seats was processed. Edge function invocations: 1.2M, bandwidth: 48GB. Download invoice in dashboard.', from: 'Vercel <billing@vercel.com>', domain: 'vercel.com' },
    { subject: 'Calendly: Subscription renewal receipt for Enterprise team ($32.00)', text: 'Your Calendly Standard subscription for scheduling customer demos was billed to card ending in 1948. View receipt online.', from: 'Calendly <billing@calendly.com>', domain: 'calendly.com' },

    // 81-100: Logistics, Travel & Scheduling
    { subject: 'United Airlines: Confirmation: Flight UA 1482 Chicago to San Francisco', text: 'Your e-ticket receipt for flight UA 1482 on October 24 is confirmed. Seat 11D (Economy Plus). Departure at 08:30 AM from Terminal 1.', from: 'United Airlines <receipts@united.com>', domain: 'united.com' },
    { subject: 'Marriott Bonvoy: Hotel reservation confirmation #8491024 (San Francisco)', text: 'Your stay at San Francisco Marriott Marquis is confirmed for Oct 24-26. 1 King Bed, High Floor. Check-in starts at 4:00 PM.', from: 'Marriott <reservations@marriott.com>', domain: 'marriott.com' },
    { subject: 'Uber: Your Thursday evening trip receipt in Chicago ($26.40)', text: 'Trip total: $26.40 charged to corporate Amex ending in 4019. Route: 100 S Wacker Dr to 222 N LaSalle St. Driver: Ahmed.', from: 'Uber Receipts <uber.us@uber.com>', domain: 'uber.com' },
    { subject: 'Lyft: Your Tuesday morning ride to O\'Hare Terminal 3 ($38.50)', text: 'Thanks for riding with Lyft. Distance: 16.4 miles. Fare: $38.50 billed to corporate Visa ending in 8491. Driver: Maria (Honda Accord).', from: 'Lyft <receipts@lyftmail.com>', domain: 'lyftmail.com' },
    { subject: 'FedEx Tracking Update: Package #78491024910 has been delivered', text: 'Shipment #78491024910 from Adafruit Industries was delivered to corporate mailroom at 2:15 PM. Signed for by receptionist.', from: 'FedEx <trackingupdates@fedex.com>', domain: 'fedex.com' },
    { subject: 'UPS Quantum View: Test equipment parcel #1Z8491024 delivered', text: 'Your package from Keysight Technologies was signed for by J. Smith at front desk. Service: UPS Next Day Air Saver.', from: 'UPS <auto-notify@ups.com>', domain: 'ups.com' },
    { subject: 'Google Calendar: Engineering Demo Day @ Friday 3:00 PM (CDT)', text: 'You have been invited to Engineering Demo Day by Marcus Vance. Where: Google Meet (meet.google.com/abc-def-ghi). Agenda: showcase v2.5 features.', from: 'Google Calendar <calendar-notification@google.com>', domain: 'google.com' },
    { subject: 'Alaska Airlines: Flight AS 482 Seattle to Chicago confirmation', text: 'Confirmation code: K9W48Q. Flight AS 482 departing SEA at 09:15 AM on October 28. Boarding gate D4. Mobile boarding pass available.', from: 'Alaska Airlines <reservations@alaskaair.com>', domain: 'alaskaair.com' },
    { subject: 'Delta Air Lines: Electronic ticket receipt for flight DL 1248 to Atlanta', text: 'Confirmation #H4910B. Flight DL 1248 Chicago O\'Hare to Atlanta Hartsfield on Nov 4. Seat 15A. Total fare: $284.10.', from: 'Delta Air Lines <ticketreceipt@delta.com>', domain: 'delta.com' },
    { subject: 'Hilton Honors: Stay confirmation #3491024 (Seattle Downtown)', text: 'Hilton Seattle Downtown reservation confirmed for Oct 28-30. King Bed with city view. Digital key available in Hilton Honors app.', from: 'Hilton Reservations <reservations@hilton.com>', domain: 'hilton.com' },

    // 101-120: Open Source, Newsletters & Tech Publications
    { subject: 'Python Software Foundation: Python 3.13 released with free-threaded build', text: 'The Python steering council announces Python 3.13. Major features: experimental free-threading without GIL and improved tracebacks.', from: 'Python PSF <news@python.org>', domain: 'python.org' },
    { subject: 'LWN.net: Weekly Edition - Memory tiering algorithms in Linux 6.12', text: 'In this week\'s edition: BPF extensible scheduler architecture, mitigating kernel memory fragmentation, and updates from the OpenSSL team.', from: 'LWN Daily <lwn@lwn.net>', domain: 'lwn.net' },
    { subject: 'PostgreSQL: Announcing PostgreSQL 17.1 security release', text: 'PostgreSQL Global Development Group released security updates addressing CVE-2026-4820 in schema search path resolution.', from: 'PostgreSQL <announce@postgresql.org>', domain: 'postgresql.org' },
    { subject: 'Rust Foundation: Rust 1.82.0 release highlights and compiler benchmarks', text: 'Rust 1.82.0 is live. Features: stabilized syntax for opaque return types and improved cargo build cache hit rates.', from: 'Rust Foundation <community@rust-lang.org>', domain: 'rust-lang.org' },
    { subject: 'ACM TechNews: Distributed database consensus algorithms under high jitter', text: 'Research roundup: Formal proofs of consensus performance in Paxos and Raft implementations across cross-continental fiber routes.', from: 'ACM <technews@acm.org>', domain: 'acm.org' },
    { subject: 'Golang Weekly: Issue 514 - Memory ballast optimizations in Go 1.24', text: 'Go 1.24 runtime updates: new garbage collector heuristics, map internal restructuring, and WebAssembly SIMD support.', from: 'Golang Weekly <editor@golangweekly.com>', domain: 'golangweekly.com' },
    { subject: 'IEEE Computer Society: Formal verification for cryptographic protocols', text: 'IEEE Software Engineering digest: Automated provers for zero-knowledge proofs and hardware security module firmware verification.', from: 'IEEE <news@computer.org>', domain: 'computer.org' },
    { subject: 'Node.js Foundation: Node.js 22 LTS codename Jod announced', text: 'Node.js 22 has entered Long Term Support. Features: built-in WebSocket client, default V8 12.4, and maglev compiler optimizations.', from: 'Node.js <announce@nodejs.org>', domain: 'nodejs.org' },
    { subject: 'Linux Weekly: Real-time PREEMPT_RT patch merged into mainline kernel', text: 'Linus Torvalds merged the long-awaited PREEMPT_RT patches into Linux 6.12, bringing native hard real-time support to mainline Linux.', from: 'Linux Weekly <editor@linuxweekly.org>', domain: 'linuxweekly.org' },
    { subject: 'InfoQ: State of Cloud-Native Architecture 2026 Trend Report', text: 'InfoQ trends report: Ephemeral development environments, OpenTelemetry standardization, and AI-assisted observability pipelines.', from: 'InfoQ <editorial@infoq.com>', domain: 'infoq.com' },

    // 121-140: Customer Support, Partnerships & Vendor Communications
    { subject: 'Zendesk: Ticket #84102 marked SOLVED by Customer Care', text: 'Ticket #84102 (API rate limit increase for enterprise tenant) has been marked as solved. Rate limits increased to 500 req/sec.', from: 'Zendesk Support <support@zendesk.com>', domain: 'zendesk.com' },
    { subject: 'Salesforce: Opportunity Stage moved to Closed-Won for Acme Corp', text: 'Enterprise contract #OPP-4891 for Acme Corp ($120k ARR) has been marked Closed-Won by Marcus Vance. Onboarding kickoff scheduled.', from: 'Salesforce <notifications@salesforce.com>', domain: 'salesforce.com' },
    { subject: 'HubSpot: Customer NPS quarterly satisfaction survey results', text: 'Your quarterly Net Promoter Score survey closed with a score of +68 across 240 enterprise respondents. Full verbatim comments attached.', from: 'HubSpot <feedback@hubspot.com>', domain: 'hubspot.com' },
    { subject: 'DocuSign Completed: Master Services Agreement signed by all parties', text: 'Envelope #d4e8-4891-2041 (MSA with Global Logistics Partners) has been signed by both executive signatories. Stored in legal archive.', from: 'DocuSign <dse@docusign.net>', domain: 'docusign.net' },
    { subject: 'Gartner: Research inquiry scheduled with Cloud Security analyst', text: 'Your 30-minute inquiry session with Gartner analyst Neil MacDonald regarding Email Security Posture Management is set for Thursday.', from: 'Gartner <inquiries@gartner.com>', domain: 'gartner.com' },
    { subject: 'RSA Conference: Speaker badge and logistics details for San Francisco', text: 'Your technical session "Deconstructing Header Deception at Scale" has been scheduled for Tuesday May 12 at 2:15 PM in Moscone West.', from: 'RSA Conference <speakers@rsaconference.com>', domain: 'rsaconference.com' },
    { subject: 'Black Hat: Call for Papers notification for Arsenal demonstration', text: 'Your tool submission for TraceXMail Open Source Mail Forensics has been accepted for demonstration at Black Hat USA Arsenal track.', from: 'Black Hat <cfp@blackhat.com>', domain: 'blackhat.com' },
    { subject: 'MITRE ATT&CK: Community contribution accepted for technique T1566', text: 'Thank you for your pull request to the MITRE ATT&CK knowledge base refining sub-technique T1566.002 (Spearphishing Link).', from: 'MITRE <attack@mitre.org>', domain: 'mitre.org' },
    { subject: 'CISA: Weekly Automated Indicator Sharing (AIS) telemetry summary', text: 'Cybersecurity and Infrastructure Security Agency weekly AIS feed summary: 142 new malicious IP addresses and domain IOCs cataloged.', from: 'CISA <ais-support@cisa.dhs.gov>', domain: 'cisa.dhs.gov' },
    { subject: 'US-CERT: Advisory AA26-281A regarding business email compromise trends', text: 'Joint cybersecurity advisory issued by CISA and FBI detailing evolving social engineering tactics targeting accounts payable departments.', from: 'US-CERT <cert@us-cert.gov>', domain: 'us-cert.gov' }
  ];

  return legit;
}
